name: Flask Parking CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run Unit Tests
      env:
        DATABASE_URL: sqlite:///test_unit.db
        FLASK_ENV: testing
        SECRET_KEY: test-secret-key
      run: |
        echo "Running Unit Tests..."
        python -m pytest tests/test_unit.py -v
        echo "Unit tests completed successfully"

    - name: Run Integration Tests
      env:
        DATABASE_URL: sqlite:///test_integration.db
        FLASK_ENV: testing
        SECRET_KEY: test-secret-key
      run: |
        echo "Running Integration Tests..."
        python -m pytest tests/test_integration.py -v
        echo "Integration tests completed successfully"

    - name: Run E2E Tests
      env:
        DATABASE_URL: sqlite:///test_e2e.db
        FLASK_ENV: testing
        SECRET_KEY: test-secret-key
      run: |
        echo "Running E2E Tests..."
        python -m pytest tests/test_e2e.py -v
        echo "E2E tests completed successfully"

    - name: Deployment Approval
      if: success()
      run: |
        echo ""
        echo "DEPLOYMENT APPROVED - ALL TESTS SUCCESSFUL"
        echo "Ready for deployment"